export const categories = [
  { id: "all", label: "All" },
  { id: "handicraft", label: "Handicraft" },
  { id: "textiles", label: "Textiles" },
  { id: "spices", label: "Food and agro" },
  { id: "stone", label: "Stone" },
];

export const products = [
  {
    id: "blue-pottery",
    sku: "JG-BP-001",
    name: "Jaipur blue pottery",
    category: "handicraft",
    pattern: "P",
    moq: "From 400 pieces",
    lead: "7 to 9 weeks after PO",
    launchScope: "v1",
    originCountry: "India",
    sourcingLocation: "Jaipur, Rajasthan",
    material: "Quartz based blue pottery body",
    finish: "Hand painted glazed finish",
    construction: "Handcrafted and hand finished",
    intendedUse: "Decorative use",
    sampleAvailable: true,
    customization: "Selected shapes, colours, and patterns on request",
    description: "Hand finished vases, planters, wall plates, tiles, and lamps in traditional Jaipur glazes.",
    image: "assets/stock/blue-pottery-alt.jpg",
    imageAlt: "Jaipur blue pottery vases on museum display, illustrative stock photo",
    westNote: "For gift and home display. Not for food unless agreed separately.",
    featured: true,
  },
  {
    id: "brass-decor",
    sku: "JG-BR-001",
    name: "Brass and copper décor",
    category: "handicraft",
    pattern: "B",
    moq: "From 300 pieces",
    lead: "4 to 6 weeks after PO",
    launchScope: "v1",
    originCountry: "India",
    sourcingLocation: "Jaipur and Rajasthan",
    material: "Brass or copper as specified",
    finish: "Finish confirmed for each product",
    construction: "Handcrafted or hand finished depending on the product",
    intendedUse: "Decorative and gift use",
    sampleAvailable: true,
    customization: "Selected finishes, sizes, and packaging on request",
    description: "Hammered bowls, trays, vases, and enamel accent pieces suited to retail and hotel gift shops.",
    image: "assets/stock/brass-decor.jpg",
    imageAlt: "Traditional Indian brass bowl, illustrative stock photo",
    westNote: "Gift and hospitality collections. Nickel free finish on request.",
    featured: true,
  },
  {
    id: "block-print-linen",
    name: "Block print linen",
    category: "textiles",
    pattern: "I",
    moq: "From 500 m",
    lead: "6 to 8 weeks",
    launchScope: "roadmap",
    westNote: "Coming soon.",
    description: "Jaipur block print patterns on linen for home textiles when this line opens.",
    image: "assets/stock/textiles.jpg",
    imageAlt: "Bagru block print textile, illustrative stock photo",
  },
  {
    id: "jaipur-quilts",
    name: "Jaipur bedding and quilts",
    category: "textiles",
    pattern: "Q",
    moq: "From 200 pieces",
    lead: "5 to 7 weeks",
    launchScope: "roadmap",
    westNote: "Coming soon.",
    description: "Light cotton quilts and bedding packed for export when this line opens.",
    image: "assets/stock/quilts.jpg",
    imageAlt: "Quilt on display, illustrative stock photo",
  },
  {
    id: "turmeric-powder",
    name: "Spices",
    category: "spices",
    pattern: "T",
    moq: "From 1 MT",
    lead: "3 to 4 weeks",
    launchScope: "roadmap",
    westNote: "Coming soon.",
    description: "Food grade spices with full documentation when this programme opens.",
    image: "assets/stock/spices.jpg",
    imageAlt: "Indian spices, illustrative stock photo",
  },
  {
    id: "basmati-rice",
    name: "Rice",
    category: "spices",
    pattern: "R",
    moq: "From 20 MT",
    lead: "4 to 5 weeks",
    launchScope: "roadmap",
    westNote: "Coming soon.",
    description: "Bulk rice exports when this programme opens.",
    image: "assets/stock/rice.jpg",
    imageAlt: "Raw basmati rice, illustrative stock photo",
  },
  {
    id: "marble-tables",
    name: "Marble inlay",
    category: "stone",
    pattern: "M",
    moq: "From 50 pieces",
    lead: "8 to 10 weeks",
    launchScope: "roadmap",
    westNote: "Coming soon.",
    description: "Marble tabletops and inlay work when this line opens.",
    image: "assets/stock/stone-marble.jpg",
    imageAlt: "White marble surface, illustrative stock photo",
  },
  {
    id: "sandstone-planters",
    name: "Sandstone garden",
    category: "stone",
    pattern: "S",
    moq: "From 100 pieces",
    lead: "6 to 8 weeks",
    launchScope: "roadmap",
    westNote: "Coming soon.",
    description: "Sandstone planters and garden pieces when this line opens.",
    image: "assets/stock/sandstone.jpg",
    imageAlt: "Sandstone garden setting, illustrative stock photo",
  },
];

export const markets = [
  "Sweden",
  "Germany",
  "Denmark",
  "Netherlands",
  "United Kingdom",
  "United Arab Emirates",
  "United States",
  "Canada",
  "Australia",
  "Other EU",
  "Other",
];

export const incoterms = [
  "EXW Jaipur (you arrange pickup)",
  "FCA named place",
  "FAS Mundra",
  "FOB Mundra (usual for bulk)",
  "CIF (we quote freight to your port)",
];
