export const categories = [
  { id: "all", label: "All categories" },
  { id: "handicraft", label: "Handicraft (launch focus)" },
  { id: "textiles", label: "Textiles and home" },
  { id: "spices", label: "Spices and agro" },
  { id: "stone", label: "Marble and stone" },
];

export const products = [
  {
    id: "blue-pottery",
    name: "Jaipur blue pottery, decorative",
    category: "handicraft",
    pattern: "P",
    moq: "MOQ 400 pcs",
    lead: "7 to 9 weeks",
    launchScope: "v1",
    description:
      "Vases, planters, wall pieces. Decorative only, not for food in v1. Drop test export packing.",
  },
  {
    id: "brass-decor",
    name: "Brass and copper décor",
    category: "handicraft",
    pattern: "B",
    moq: "MOQ 300 pcs",
    lead: "4 to 6 weeks",
    launchScope: "v1",
    description:
      "Gift and hospitality décor, lacquered interiors, nickel free on request. No jewelry in v1.",
  },
  {
    id: "block-print-linen",
    name: "Block print linen collections",
    category: "textiles",
    pattern: "I",
    moq: "MOQ 500 m",
    lead: "6 to 8 weeks",
    launchScope: "roadmap",
    description: "Roadmap. EU homeware when desk expands.",
  },
  {
    id: "jaipur-quilts",
    name: "Jaipur razai and layered bedding",
    category: "textiles",
    pattern: "Q",
    moq: "MOQ 200 pcs",
    lead: "5 to 7 weeks",
    launchScope: "roadmap",
    description: "Roadmap. Not v1.",
  },
  {
    id: "turmeric-powder",
    name: "Turmeric and spice blends",
    category: "spices",
    pattern: "T",
    moq: "MOQ 1 MT",
    lead: "3 to 4 weeks",
    launchScope: "roadmap",
    description: "Roadmap. Agro compliance separate track.",
  },
  {
    id: "basmati-rice",
    name: "Basmati and specialty rice",
    category: "spices",
    pattern: "R",
    moq: "MOQ 20 MT",
    lead: "4 to 5 weeks",
    launchScope: "roadmap",
    description: "Roadmap. Not v1 craft launch.",
  },
  {
    id: "marble-tables",
    name: "Marble inlay and table tops",
    category: "stone",
    pattern: "M",
    moq: "MOQ 50 pcs",
    lead: "8 to 10 weeks",
    launchScope: "roadmap",
    description: "Roadmap. Stone programme later.",
  },
  {
    id: "sandstone-planters",
    name: "Sandstone planters and garden",
    category: "stone",
    pattern: "S",
    moq: "MOQ 100 pcs",
    lead: "6 to 8 weeks",
    launchScope: "roadmap",
    description: "Roadmap. Heavy freight later.",
  },
];

export const markets = [
  "Sweden",
  "Germany",
  "Denmark",
  "Netherlands",
  "United Kingdom",
  "United Arab Emirates",
  "United States",
  "Canada",
  "Australia",
  "Other EU",
  "Other",
];

export const incoterms = [
  "EXW Jaipur",
  "FCA (named place)",
  "FAS Mundra",
  "FOB Mundra",
  "CIF (named port)",
];
