export const categories = [
  { id: "all", label: "All categories" },
  { id: "handicraft", label: "Handicraft (launch focus)" },
  { id: "textiles", label: "Textiles & home" },
  { id: "spices", label: "Spices & agro" },
  { id: "stone", label: "Marble & stone" },
];

export const products = [
  {
    id: "blue-pottery",
    name: "Jaipur blue pottery — decorative",
    category: "handicraft",
    pattern: "P",
    moq: "MOQ 400 pcs",
    lead: "7–9 weeks",
    launchScope: "v1",
    description:
      "Vases, planters, wall pieces. Decorative only — not for food in v1. Drop-test export packing.",
  },
  {
    id: "brass-decor",
    name: "Brass & copper décor",
    category: "handicraft",
    pattern: "B",
    moq: "MOQ 300 pcs",
    lead: "4–6 weeks",
    launchScope: "v1",
    description:
      "Gift and hospitality décor — lacquered interiors, nickel-free on request. No jewelry in v1.",
  },
  {
    id: "block-print-linen",
    name: "Block-print linen collections",
    category: "textiles",
    pattern: "I",
    moq: "MOQ 500 m",
    lead: "6–8 weeks",
    launchScope: "roadmap",
    description: "Roadmap — EU homeware when desk expands.",
  },
  {
    id: "jaipur-quilts",
    name: "Jaipur razai & layered bedding",
    category: "textiles",
    pattern: "Q",
    moq: "MOQ 200 pcs",
    lead: "5–7 weeks",
    launchScope: "roadmap",
    description: "Roadmap — not v1.",
  },
  {
    id: "turmeric-powder",
    name: "Turmeric & spice blends",
    category: "spices",
    pattern: "T",
    moq: "MOQ 1 MT",
    lead: "3–4 weeks",
    launchScope: "roadmap",
    description: "Roadmap — agro compliance separate track.",
  },
  {
    id: "basmati-rice",
    name: "Basmati & specialty rice",
    category: "spices",
    pattern: "R",
    moq: "MOQ 20 MT",
    lead: "4–5 weeks",
    launchScope: "roadmap",
    description: "Roadmap — not v1 craft launch.",
  },
  {
    id: "marble-tables",
    name: "Marble inlay & table tops",
    category: "stone",
    pattern: "M",
    moq: "MOQ 50 pcs",
    lead: "8–10 weeks",
    launchScope: "roadmap",
    description: "Roadmap — stone programme later.",
  },
  {
    id: "sandstone-planters",
    name: "Sandstone planters & garden",
    category: "stone",
    pattern: "S",
    moq: "MOQ 100 pcs",
    lead: "6–8 weeks",
    launchScope: "roadmap",
    description: "Roadmap — heavy freight later.",
  },
];

export const markets = [
  "Sweden",
  "Germany",
  "Denmark",
  "Netherlands",
  "United Kingdom",
  "United Arab Emirates",
  "United States",
  "Canada",
  "Australia",
  "Other EU",
  "Other",
];

export const incoterms = [
  "EXW Jaipur",
  "FCA (named place)",
  "FAS Mundra",
  "FOB Mundra",
  "CIF (named port)",
];
